platform:
  - x64
environment:
  matrix: 
    - nodejs_version: 6

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version		  
  - set CI=true		  
  - npm install -g npm@latest		  
  - set PATH=%APPDATA%\npm;%PATH%		  
  - npm install

build_script:
  - npm test
  - npm run build-app
  - npm run build-win