platform:
  - x64
environment:
  matrix: 
    - nodejs_version: 6.9.1 x64

cache:
  - node_modules

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version		  
  - set CI=true		  
  - npm install -g npm@latest		  
  - set PATH=%APPDATA%\npm;%PATH%		  
  - npm install

test_script:
  - npm test

matrix:
  fast_finish: false

build:
  - npm run build-app
  - npm run build-win