platform:
  - x64

cache:
  - node_modules

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64

build_script:
  - npm test
  - npm run build-app
  - npm run build-win