language: node_js
node_js:
  - "6.9"

platform:
  - x64

cache:
  - node_modules

install:
  - ps: Install-Product node 7 x64
  - yarn install
  - yarn add electron-builder@next --dev # force install next version to test electron-builder

build_script:
  - npm test
  - yarn run build-app
  - yarn run build-win

test: off